name: "Publish Markdown to Confluence"
description: "Publishes a Markdown file to Confluence"
inputs:
  file_path:
    description: "Path to the Markdown file to publish"
    required: true
    default: "README.md"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "book"
  color: "blue"